version: '3.8'
services:
  db:
    image: mysql:8.0
    volumes:
      - mysql-db-store:/var/lib/mysql
      - ./docker/db/logs:/var/log/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=pa55
      - MYSQL_DATABASE=salesworker
      - MYSQL_USER=saito
      - MYSQL_PASSWORD=pa55
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
    command: --innodb-use-native-aio=0

volumes:
  mysql-db-store:
